pipeline {
    agent any
    stages {
        stage('git repo clone') {
            steps {
                git branch: 'main', url:'https://github.com/sud20010709/dyw-backend.git'
            }
        }
        stage('clean') {
            steps {
                sh "mvn clean"
            }
        }
        stage('package') {
            steps {
                sh "mvn package"
            }
        }
//         stage('docker compose') {
//             steps {
//                 sh "docker-compose up"
//             }
//         }
//         stage('docker build') {
//             steps {
//                 sh "docker build -t driveyourway ."
//             }
//         }
        stage('docker run') {
             steps {
                 sh "docker run -p 5555:5555 --name driveyourway-backend --link mysql-driveyourway -d driveyourway-backend:1.0"
             }
        }
    }
}